version: 2.1

jobs:
    Test:
        docker:
            - image: svalinn/pymoab-visit-py2-18.04
        steps:
            - checkout
            - run: pytest

workflows:
    build:
        jobs:
            - Test
